[Design] [MIS] Introduction
arkinmodi/project-sayyara pull request #388
Opened 2023-01-07 21:24 UTC by joyxiao99

close https://github.com/arkinmodi/project-sayyara/issues/361

2023-01-07 21:28 UTC, LeonSo7 commented on docs/Design/SoftDetailedDes/MIS.tex
> +is to create a progressive web application for independent automotive repair shop industry which
We can probably copy the project description from the SRS. Something like:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/34189743/211170961-eb36b389-f6a4-454a-b71c-973c40ef7711.png">
...

2023-01-07 21:41 UTC, LeonSo7 requested changes

2023-01-07 21:41 UTC, LeonSo7 commented on docs/Design/SoftDetailedDes/MIS.tex
> +to interact in a more efficient and effective manner. Key features include booking appointments,
Looks like there are a few key features we are missing - e.g., finding a service/shop. Maybe we can expand on and separate the features by user type. Theres shop management and vehicle owner features.

2023-01-07 21:41 UTC, LeonSo7 commented on docs/Design/SoftDetailedDes/MIS.tex
> +to interact in a more efficient and effective manner. Key features include booking appointments,
If you want, you can probably also pull this from the SRS

2023-01-07 21:42 UTC, joyxiao99 commented on docs/Design/SoftDetailedDes/MIS.tex
> +to interact in a more efficient and effective manner. Key features include booking appointments,
i said finding a shop and shop management just seems meh

2023-01-07 21:44 UTC, joyxiao99 commented on docs/Design/SoftDetailedDes/MIS.tex
> +to interact in a more efficient and effective manner. Key features include booking appointments,
looooll theres a huge paragraph from the SRS i guess ill just copy and paste that in. i swear the intro is just completion marks tho

2023-01-08 05:31 UTC, LeonSo7 commented on docs/Design/SoftDetailedDes/MIS.tex
> +Ultimately, Sayyara will significantly improve the auto repair experience for both independent auto
```suggestion
This document will outline the modules and specifications supporting these key features.
```
Can we tie the end of the intro back in maybe?
Ya, its a bit long, can we make the description more brief by giving an intro into the modules rather than features? Idk

2023-01-10 20:59 UTC, arkinmodi commented on docs/Design/SoftDetailedDes/MIS.tex
> +MIS will detail specifications for the project described above.
Should add `MIS` to the "Symbols, Abbreviations and Acronyms" section. Can you fill out this section? Just copy the table from the MG into the MIS and we can remove the extra's during polishing.

2023-01-10 20:59 UTC, arkinmodi approved these changes

2023-01-11 03:14 UTC, LeonSo7 approved these changes

2023-01-11 19:46 UTC, merged