[Design] [MIS] Employee Management Module
arkinmodi/project-sayyara pull request #421
Opened 2023-01-16 19:39 UTC by joyxiao99

close https://github.com/arkinmodi/project-sayyara/issues/366

2023-01-16 21:50 UTC, arkinmodi requested changes

2023-01-16 21:50 UTC, arkinmodi commented on docs/Design/SoftDetailedDes/MIS.tex
> +\section{MIS of Employee Management Module} \label{mEmployeeManagement}
```suggestion
\newpage

\section{MIS of Employee Management Module} \label{mEmployeeManagement}
```

2023-01-16 21:50 UTC, arkinmodi commented on docs/Design/SoftDetailedDes/MIS.tex
> +			getAllEmployees & String                     & List<$Employee$>      & ~                   \\
```suggestion
			getAllEmployees & String                     & List$<$Employee$>$    & ~                   \\
```

2023-01-16 21:50 UTC, arkinmodi commented on docs/Design/SoftDetailedDes/MIS.tex
> +			updateEmployee  & String, UpdateEmployeeType & UserNotFoundException                       \\
```suggestion
updateEmployee  & String, UpdateEmployeeType & ~                  & UserNotFoundException \\
```

2023-01-16 21:50 UTC, arkinmodi commented on docs/Design/SoftDetailedDes/MIS.tex
> +		      None.$
```suggestion
	\item output: $out :=$ List of employees from the shop database table associated with the $shopId$, else
	      None.
```

2023-01-16 21:50 UTC, arkinmodi commented on docs/Design/SoftDetailedDes/MIS.tex
> +\end{itemize}
Based on what Leon said yesterday, deleting an employee might not be what we want to do. 
cc: @LeonSo7

<img width="1207" alt="Screenshot 2023-01-16 at 4 48 07 PM" src="https://user-images.githubusercontent.com/16737086/212770500-e2e81caf-0825-405e-8557-d4320a8b506b.png">

2023-01-16 21:50 UTC, arkinmodi commented on docs/Design/SoftDetailedDes/MIS.tex
> +			getEmployeeById & String                     & $Employee$            & ~                   \\
```suggestion
			getEmployeeById & String                     & Employee              & ~                   \\
```

2023-01-17 04:03 UTC, LeonSo7 commented on docs/Design/SoftDetailedDes/MIS.tex
> +\noindent removeEmployee($employeeId$):
```suggestion
\noindent suspendEmployee($employeeId$):
```

2023-01-17 04:04 UTC, LeonSo7 commented on docs/Design/SoftDetailedDes/MIS.tex
> +			removeEmployee  & String                     & ~                  & ~                     \\
```suggestion
			suspendEmployee  & String                     & ~                  & ~                     \\
```

2023-01-17 16:23 UTC, arkinmodi approved these changes

2023-01-17 16:23 UTC, arkinmodi commented on docs/Design/SoftDetailedDes/MIS.tex
> +	\begin{tabular}{|l|l|l|}
I'm updating these in my MIS for Quotes PR.

```suggestion
	\begin{tabular}{|p{0.25\textwidth}|p{0.25\textwidth}|p{0.40\textwidth}|}
```

2023-01-17 16:59 UTC, merged