[SRS] Add FR for employee invitation
arkinmodi/project-sayyara pull request #91
Opened 2022-10-03 04:19 UTC by LeonSo7

2022-10-03 20:42 UTC, joyxiao99 commented on docs/SRS/SRS.tex
> +	\item [{BE}1.] The shop owner wants to invite and employee to their shop
'invite an employee'

2022-10-04 03:42 UTC, LeonSo7 commented
Do not merge until #95 is merged.

2022-10-04 03:42 UTC, LeonSo7 commented on docs/SRS/SRS.tex
> +	\item [{BE}1.] The shop owner wants to invite and employee to their shop
Fixed, thanks for catching that.

2022-10-04 19:04 UTC, arkinmodi requested changes

2022-10-05 02:22 UTC, LeonSo7 commented on docs/SRS/SRS.tex
> +	      \end{enumerate}
Updated

2022-10-05 15:08 UTC, arkinmodi approved these changes

2022-10-05 15:51 UTC, merged